---
- name: Handson Activity 8b by Isaac Sapelino
  hosts: elasticsearch
  tags: elasticsearch, ubuntu, centos
  tasks:
    - name: Include global variables
      include_vars:
        file: config.yml

    - name: Install Docker dependencies (Ubuntu)
      include_role:
        name: installubuntupkg
      vars:
        package:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3
          - python3-pip
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install Docker (Ubuntu)
      include_role:
        name: installubuntupkg
      vars:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        filename: "docker-ce"
        package:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        service: docker
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install Docker (CentOS)
      include_role:
        name: installcentospkg
      vars:
        src: "{{ docker_repo }}"
        dest: "/etc/yum.repos.d//docker-ce.repo"
        package:
          - docker-ce
          - python3
          - python3-pip
        service: docker
      when: ansible_facts['distribution'] == 'CentOS'

    - name: Stop firewalld (CentOS)
      include_role:
        name: stopfirewalld
      when: ansible_facts['distribution'] == 'CentOS'

    - name: Stop UFW (Ubuntu)
      include_role:
        name: stopufw
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: "Pip: Installing Docker Modules"
      include_role:
        name: pipinstall
      vars:
        pippackage: docker

    - name: Add user to docker group
      include_role:
        name: dockergroup

    - name: Build and Run Elasticsearch, Logstash, and Kibana (ELK Stack)
      include_role:
        name: installelk

